[tool.poetry]
name = "python-helloworld"
version = "1.0.0"
description = ""
authors = ["David Barnett <davidbarnett2@gmail.com>", "Luis Díaz <luis@drconopoima.com>"]

[tool.poetry.dependencies]
python = "*"